services:
  {~PROJECT_NAME~}_nodejs:
    container_name: ${PROJECT_NAME}_nodejs
    build:
      context: ../
      dockerfile: docker_nodejs/images/nodejs/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    restart: unless-stopped
    volumes:
      - ../:/usr/src/app
      - ./images/nodejs/npm_start.sh:/usr/src/npm_start.sh
    ports:
      - ${PORT_NODE_EXT}:${PORT_NODE_INT}
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    networks:
      - ${PROJECT_NAME}-network

networks:
  {~PROJECT_NAME~}-network:
    driver: bridge
