services:
  nodejs:
    container_name: ${PROJECT_TAG}_nodejs
    build:
      context: ../
      dockerfile: docker_nodejs/images/nodejs/Dockerfile
    restart: unless-stopped
    volumes:
      - ../:/usr/src/app
      - ./images/nodejs/npm_start.sh:/usr/src/npm_start.sh
    ports:
      - ${PORT_NODE_EXT}:${PORT_NODE_INT}
    environment:
      CHOKIDAR_USEPOLLING: true
      NODE_VERSION: ${NODE_VERSION}
    stdin_open: true
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
