version: "3.7"

services:
  {~PROJECT_NAME~}_nginx:
    container_name: {~PROJECT_NAME~}_nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - ${PORT_NGINX}:80
    volumes:
      - ../:/var/www/app
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - {~PROJECT_NAME~}_mysql
      - {~PROJECT_NAME~}_php_fpm
    networks:
      - {~PROJECT_NAME~}-network

  {~PROJECT_NAME~}_php_fpm:
    container_name: {~PROJECT_NAME~}_php_fpm
    build:
      args:
        user: doc
        uid: 1000
      context: ./images/php
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT_PHP_FPM}:9000
    volumes:
      - ../:/var/www/app
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./config/php/bashrc:/home/lara/.bashrc
    links:
      - {~PROJECT_NAME~}_mysql
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - {~PROJECT_NAME~}-network

  {~PROJECT_NAME~}_mysql:
    container_name: {~PROJECT_NAME~}_mysql
    image: mysql
    restart: unless-stopped
    ports:
      - ${PORT_DB}:3306
    environment:
      MYSQL_HOST: {~PROJECT_NAME~}_mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_volumes/mysql:/var/lib/mysql
      - ./images/mysql:/docker-entrypoint-initdb.d
    networks:
      - {~PROJECT_NAME~}-network

  {~PROJECT_NAME~}_myadmin:
    container_name: {~PROJECT_NAME~}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: {~PROJECT_NAME~}_mysql
    ports:
      - ${PORT_MYADMIN}:80
    volumes:
      - /sessions
    external_links:
      - {~PROJECT_NAME~}_mysql
    depends_on:
      - {~PROJECT_NAME~}_mysql
    networks:
      - {~PROJECT_NAME~}-network

networks:
  {~PROJECT_NAME~}-network:
    driver: bridge
