services:
  nginx:
    container_name: ${PROJECT_TAG}_nginx
    build:
      args:
        PROJECT_TAG: ${PROJECT_TAG}
        HOST_NAME: ${HOST_NAME}
      context: images/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT_NGINX}:80
    volumes:
      - ../:/var/www/app
    links:
      - mysql
      - php_fpm
    networks:
      - local_network

  php_fpm:
    container_name: ${PROJECT_TAG}_php_fpm
    build:
      args:
        user: doc
        uid: 1000
        PHP_VERSION: ${PHP_VERSION}
        XDEBUG_VERSION: ${XDEBUG_VERSION}
      context: images/php
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT_PHP_FPM}:9000
    volumes:
      - ../:/var/www/app
      - ./images/php/config/bash_history:/home/doc/.bash_history
      - ./images/php/config/bashrc:/home/doc/.bashrc
      - ./images/php/config/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
      - ./images/php/config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./images/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - mysql
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_network

  mysql:
    container_name: ${PROJECT_TAG}_mysql
    image: mysql
    restart: unless-stopped
    ports:
      - ${PORT_DB}:3306
    environment:
      MYSQL_HOST: ${PROJECT_TAG}_mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_volumes/mysql:/var/lib/mysql
      - ./images/mysql:/docker-entrypoint-initdb.d
    networks:
      - local_network

  myadmin:
    container_name: ${PROJECT_TAG}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${PROJECT_TAG}_mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${PORT_MYADMIN}:80
    volumes:
      - /sessions
    external_links:
      - mysql
    depends_on:
      - mysql
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
